### ISSUE TITLE
gRPC模式下serviceName设置

### ISSUE THREAD

**Issue by Bryan2333** [teddysun/xray-plugin-android#1]
从V2fly的文档上来看，gRPC模式下可以设置serviceName进行分流，但是插件里没有这个选项。请问能否将serviceName的选项添加回去，另外v2ray-plugin那边也没有。

**Comment by teddysun** [comment]
Android 欢迎 PR，将 serviceName 的选项添加进来。
精力有限，这个功能不再对应。

**Comment by dmirubtsov** [comment]
PR: https://github.com/teddysun/xray-plugin-android/pull/4
